version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/kardasch
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: