version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/kardasch
      - GRAPHQL_PATH=/graphql
      - JWT_ACCESS_SECRET=your-access-secret-key-change-in-production
      - JWT_REFRESH_SECRET=your-refresh-secret-key-change-in-production
      - JWT_ACCESS_EXPIRY=15m
      - JWT_REFRESH_EXPIRY=7d
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
